### ISSUE TITLE
dsctl ignores custom path and only uses paths in defaults.inf

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#4459]
**Issue Description**

If you set a custom backup directory during installation:

    [general]
    config_version = 2
    full_machine_name = localhost.localdomain
    start = True

    [slapd]
    port = 389
    backup_dir = /var/opt/dirsrv/slapd-{instance_name}/bak

The directory is correctly created, but when you run the CLI command to list the backups it fails:

    # dsctl -j localhost backups
    {
        "desc": "[Errno 2] No such file or directory: '/var/lib/dirsrv/slapd-localhost/bak'"
    }

Notice it looks in "/var/lib/dirsrv", and not "/var/opt/dirsrv".  This is because dsctl accesses the instance in an offline mode, so it only get the server's paths from defaults.inf.  We should attempt to get the server's paths from DSEldif class, only if that fails should we fallback to defaults.inf.

**Comment by mreynolds389** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1901020

**Comment by Firstyear** [comment]
Some days I regret supporting all the features of the original setup-ds.pl, like custom paths because it leads to things like this, but also, this would break SELinux policy too ....

But yes, I think in this case we'd need to read the dse.ldif in offline mode too.

**Comment by mreynolds389** [comment]
> Some days I regret supporting all the features of the original setup-ds.pl, like custom paths because it leads to things like this, but also, this would break SELinux policy too ....

Actually the installer applies the selinux labels and it is correct after install.

**Comment by mreynolds389** [comment]
> > Some days I regret supporting all the features of the original setup-ds.pl, like custom paths because it leads to things like this, but also, this would break SELinux policy too ....
> 
> Actually the installer applies the selinux labels and it is correct after install.

Actually it looks like it does not apply the correct label, and it looks like the uninstall is not removing the custom path :-/

**Comment by Firstyear** [comment]
During uninstall we probably read from defaults, not dse.ldif as well. 

And during install we don't label any files because we assume the system policy exists and will label them correctly for us. 

IMO the issue is the user needlessly using /var/opt instead of /var/lib - unless they have a really really really compelling, amazing reason, I think they should not be doing this (and it's why there was a recent change to "hide" the file path options in the .inf template, so that people can't see that these changes are possible).

**Comment by vashirov** [comment]
I've seen customers migrating from DSEE trying to adapt their habits/tooling/infra in a minimal way to use RHDS. DSEE can be installed in an arbitrary directory like `/opt/inst1/`, but RHDS/389-DS can not (or rather should not, because SELinux brings additional benefits). 
 
One actually compelling reason is testing. For example, openldap can be started by a non-root user with `slapd.conf` that contains arbitrary paths. It is used this way in python-ldap, gssproxy, sssd and maybe other projects. On the other hand, 389-ds instance can't be created by a non-root user, unless it's a prefix build, where non-root writable paths are defined in `defaults.inf`. 
I did an experiment with dscreate template some time ago: https://bugzilla.redhat.com/show_bug.cgi?id=1872451#c3
It is possible to install 389-ds instance by a non-root user, but only after massaging `defaults.inf` and crafting a special template that turns off SELinux and systemd support.

I think it's worth to support non-root installations for testing purposes so that upstream and downstream projects can choose LDAP server to test against instead of having openldap as the only option.

**Comment by yonecle** [comment]
Hi,

How's this issue going?
Is there any prospect of fixing it in 1.4.3 or the next version?

**Comment by Firstyear** [comment]
@yonecle "it's difficult" is the answer. There is partial support for this already in how paths work if you are *online* aka connected to the instance than we can retrieve the value from cn=config. This should work for dsconf and dsidm. 

dsctl is tricker, since we'd need to add support to parse the ldif and have fall backs if it's not there. Line 153 of src/lib389/lib389/paths.py is where we'd need to add the dse.ldif reading support.

**Comment by mreynolds389** [comment]
12b25060b..e8a4c61b7  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
e77ced1f1..9e5fe7aec  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
