### ISSUE TITLE
IPA topologysegments not created when replica is installed (using @389ds/389-ds-base-nightly)

### ISSUE THREAD

**Issue by flo-renaud** [389ds/389-ds-base#4478]
**Issue Description**
When an IPA replica is installed, the topologysegments are not created anymore if 389-ds is installed from @389ds/389-ds-base-nightly copr repo.

The regression was introduced in the master branch of 389-ds-base, between the commits ce7beae4d (no issue) and 
7d2f95dc5 (issue seen).
See for instance IPA nightly test in PR #[574](https://github.com/freeipa-pr-ci2/freeipa/pull/574): test_topology_TestTopologyOptions ([report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/39c44726-37e3-11eb-a333-fa163e03489e/report.html) and [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/39c44726-37e3-11eb-a333-fa163e03489e/)).

**Package Version and Platform:**
 - Platform: Fedora 32
 - Package and version: 389-ds-base-2.0.1-20201206gitdec149b4c.fc32.x86_64

**Steps to Reproduce**
1. Install ipa server: `ipa-server-install --domain ipa.test --realm IPA.TEST -a $PASSWORD -p $PASSWORD -U`
2. Install ipa client on the replica: `ipa-client-install --domain ipa.test --realm IPA.TEST --server $SERVER_IP --principal admin --password $PASSWORD -U`
3. install the replica: `kinit admin; ipa-replica-install -U`
4. Check the topologysegments on any node: `ipa topologysegment-find domain`
No segment is found:
```
# ipa topologysegment-find domain
------------------
0 segments matched
------------------
----------------------------
Number of entries returned 0
----------------------------
```

**Expected results**
The replica installation should create a segment server.ipa.test-to-replica.ipa.test.

Companion issue on IPA side:https://pagure.io/freeipa/issue/8611

**Comment by flo-renaud** [comment]
In summary the problem was introduced in one of these commits: (more recent top)
- [7d2f95d](https://github.com/389ds/389-ds-base/commit/7d2f95dc505626be29fea3aae57695bb9b0defdb) Issue 4243 - Fix test: SyncRepl plugin provides a wrong cookie
- [b721951](https://github.com/389ds/389-ds-base/commit/b7219518d0520c4d5db1f88ad0f136eb7ba81765)Issue 4464 - RFE - clang with ds+asan+rust
- [782e6c1](https://github.com/389ds/389-ds-base/commit/782e6c1efacc82d752fa65e06c19fa40160bcb01)Issue 4105 - Remove python.six (fix regression) 
- [a5029c8](https://github.com/389ds/389-ds-base/commit/a5029c8091d4522be6da0c0594ccfc9c9db7e64c)Issue 4384 - Use MONOTONIC clock for all timing events and conditions 
- [a98fe54](https://github.com/389ds/389-ds-base/commit/a98fe54292e9b183a2163efbc7bdfe208d4abfb0)Issue 4418 - ldif2db - offline. Warn the user of skipped entries
- [f1243f7](https://github.com/389ds/389-ds-base/commit/f1243f7cba78a9c0e85246d0f8f8d237a9493071) Issue 4243 - Fix test: SyncRepl plugin provides a wrong cookie (#4467)

**Comment by flo-renaud** [comment]
Re-tested with @tbordaz build https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/build/1818078/ that does not include the fix for 4384, and the scenario works perfectly. The conclusion is that the regression is caused by this commit: a5029c8 Issue 4384 - Use MONOTONIC clock for all timing events and conditions

**Comment by mreynolds389** [comment]
What is an IPA segment?  I have no idea what is actually going wrong on the DS side as I don't understand what the actual problem is.  Is it failing to create a replication agreement?  Do we have any DS logs showing the "problem"?

**Comment by tbordaz** [comment]
The segment is a topology plugin object. A segment can be uni or bi directional. A uni directional segment is basically a replication agreement. A bi-directional segment is two RA H1<-->H2.
The role of topology plugin, running on H1, is to track the creation of a new host H2 in the topology to establish automatically a RA H1->H2.
the RA will be mapped by a segment entry in the replicated domain. A task of topology plugin is to "merge" two uni-directional RA into a single bi-directional one.

The problem here is that although H1 detects the creation of H2 host, it does not create the segment (I am not sure for the RA)

**Comment by flo-renaud** [comment]
@mreynolds389 
The topology plugin is a 389ds plugin provided by ipa source code: https://github.com/freeipa/freeipa/tree/master/daemons/ipa-slapi-plugins/topology
The design is available [here](https://www.freeipa.org/page/V4/Manage_replication_topology) if you're interested. We're not sure yet if the topology plugin needs to be adapted to the new clock code or if the issue is on ds side, and @tbordaz is currently investigating.

**Comment by mreynolds389** [comment]
I will look into that doc, thanks!  This is definitely a strange issue though since the clock change was just for event handling and condition variables.  It should not impact the creation of entries, or searches, mods, deletes, etc. Regardless, there is nothing that should need to be done on the IPA side as this change should have been transparent.

**Comment by Firstyear** [comment]
> The segment is a topology plugin object. A segment can be uni or bi directional. A uni directional segment is basically a replication agreement. A bi-directional segment is two RA H1<-->H2.
> The role of topology plugin, running on H1, is to track the creation of a new host H2 in the topology to establish automatically a RA H1->H2.
> the RA will be mapped by a segment entry in the replicated domain. A task of topology plugin is to "merge" two uni-directional RA into a single bi-directional one.
> 
> The problem here is that although H1 detects the creation of H2 host, it does not create the segment (I am not sure for the RA)

how is the plugin "detecting" changes? It seems suspicious here that a change to the internal clock source could affect this, so I'm wondering how the topology plugin actually detects changes in order to act on that. That would indicate to me that we either put monotonic in a user facing clock position where it becomes inconsistent (because each server has monotonic at different time points even though both are continually advancing).

**Comment by tbordaz** [comment]
The problem is that topology plugin uses slapi_eq_once to differ its initialization (upload of the shared config).
It calls '_time_'  (i.e. CLOCK_REALTIME) to schedule the init where now with https://github.com/389ds/389-ds-base/issues/4384 it must use CLOCK_MONOTONIC (i.e. slapi_current_rel_time_t).
In that case the topology plugin initialization has not yet occurred when the replica host is add as a master and so the segment is not created.

The problem now is that #4384 changed plugin API and applications need to be updated. Also there is no programmatic way to detect which interface to use (monotonic, realtime).

**Comment by tbordaz** [comment]
event queue is now using monotonic time. If a plugin used to call slapi_eq_repeat or slapi_eq_once it has to move to monotonic time.

slapi_waitcond_var  now returns NULL. We may need to keep supporting the old interface.

**Comment by Firstyear** [comment]
Can you link to the section of the topology plugin that does this?

**Comment by tbordaz** [comment]
@Firstyear this is https://github.com/freeipa/freeipa/blob/master/daemons/ipa-slapi-plugins/topology/topology_util.c#L1595

**Comment by Firstyear** [comment]
@tbordaz Given how tightly FreeIPA binds to a 389-ds version, I think this should be fixed in the IPA topology plugin.

**Comment by tbordaz** [comment]
@Firstyear I agree with you we do need the monotonic fix. It remains that slap_eq* are part of plugin api and at the moment it breaks slapi-nis and topology. The fix for them is very simple. My concern is others customer plugins that would use those calls and that will get broken.
@mreynolds389 created a clever mechanism to detect if a timer is realtime/monotonic that could workaround the compatibility issue. It is under test.

**Comment by Firstyear** [comment]
@tbordaz mreynolds sent me a copy of the patch in email, and we discussed and have a better solution :)

**Comment by mreynolds389** [comment]
Already fixed
