### ISSUE TITLE
Failure on s390x: 'Fails to split RDN "o=pki-tomcat-CA" into components'

### ISSUE THREAD

**Issue by tjaalton** [389ds/389-ds-base#4563]
**Issue Description**

pkispawn fails on s390x, and this is from the 389 log:

[22/Jan/2021:09:04:35.687297399 +0000] - ERR - attrcrypt_cipher_init - No symmetric key found for cipher AES in backend pki-tomcat-CA, attempting to create one...
[22/Jan/2021:09:04:35.692412357 +0000] - INFO - attrcrypt_cipher_init - Key for cipher AES successfully generated and stored
[22/Jan/2021:09:04:35.692791984 +0000] - ERR - attrcrypt_cipher_init - No symmetric key found for cipher 3DES in backend pki-tomcat-CA, attempting to create one...
[22/Jan/2021:09:04:35.697798362 +0000] - INFO - attrcrypt_cipher_init - Key for cipher 3DES successfully generated and stored
[22/Jan/2021:09:04:35.887915222 +0000] - ERR - entry_get_rdn_mods - Fails to split RDN "o=pki-tomcat-CA" into components

This started after 1.4.4.4, and the error message would suggest that something is wrong with commit 2ccd0bed4e60e.

 s390x is big-endian, and other architectures don't have this issue, so endianness might have something to do with it?

**Package Version and Platform:**
 - Platform: Debian/Ubuntu
 - Package and version: 389-ds-base-1.4.4.10-1

**Comment by tjaalton** [comment]
reverting that commit allowed pkispawn to work again

**Comment by slyon** [comment]
I can confirm the test works again after the above mentioned commit is reverted.

Here are the logs of the pkispawn test:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-hirsute-slyon-testing/hirsute/s390x/d/dogtag-pki/20210122_114408_9ecb1@/log.gz

**Comment by mreynolds389** [comment]
To help reproduce this internally (outside of pkispawn), what LDAP operation is failing?  And what is that operation trying to do?

**Comment by tjaalton** [comment]
'INFO: Adding aci into o=pki-tomcat-CA'

and then it fails. Trying to look deeper, but a quick grep gives no hits in dogtag..

**Comment by mreynolds389** [comment]
> 'INFO: Adding aci into o=pki-tomcat-CA'
> 
> and then it fails. Trying to look deeper, but a quick grep gives no hits in dogtag..

The DS access log (/var/log/dirsrv/slapd-INSTANCE/access) will show an update that fails with "err=1", what is that operation?  MOD, MODRDN, ADD, etc, ?

**Comment by tjaalton** [comment]
ah yes

[22/Jan/2021:09:04:35.884128951 +0000] conn=6 op=205 ADD dn="ou=csusers,cn=config"
[22/Jan/2021:09:04:35.887616212 +0000] conn=6 op=205 RESULT err=0 tag=105 nentries=0 wtime=0.000017487 optime=0.003488410 etime=0.003504799
[22/Jan/2021:09:04:35.887639721 +0000] conn=6 op=206 MOD dn="o=pki-tomcat-CA"
[22/Jan/2021:09:04:35.893833587 +0000] conn=6 op=206 RESULT err=1 tag=103 nentries=0 wtime=0.000008164 optime=0.006193627 etime=0.006200604

**Comment by tbordaz** [comment]
@mreynolds is right, the access logs showing the error would definitely help. At the time pkispaw is launched, is the topology containing several instances (replication) ?

If the failing operation is MODRDN, would you confirm that the 'newrdn' is not empty ?

**Comment by tjaalton** [comment]
this is from a deb package autopkgtest, which just sets up slapd (single instance), then runs pkispawn on it, no magic.. and the log snippet is above, 'MOD dn="o=pki-tomcat-CA"' fails

**Comment by tjaalton** [comment]
here is the full access log https://paste.ubuntu.com/p/pjqj8NPzZj/

**Comment by tbordaz** [comment]
@tjaalton thanks for the information. I agree that  big/small endian could be part of the problem. Such deployment on x86_64 is very common. I will try to reproduce. At the moment I suspect mozldap_ldap_explode() to return an empty results when processing o=pki-tomcat-CA (bad memcpy?).

**Comment by Firstyear** [comment]
Is it a pointer or value size mismatch? That would certainly be affected by be/le here ...

**Comment by tbordaz** [comment]
The problem appears in slapi-pblock-get, that reads a 8bytes field (unsigned long) and store it into a 8 bytes files (void *).
This is the expected behaviour but it actually store the upper 4 bytes of destination.
<pre>
216	int32_t
217	entry_get_rdn_mods(Slapi_PBlock *pb, Slapi_Entry *entry, CSN *csn, int repl_op, Slapi_Mods **smods_ret)
218	{
219	    unsigned long op_type = SLAPI_OPERATION_NONE;
...
236	
237	    /* First get the RDNs of the operation */
238	    slapi_pblock_get(pb, SLAPI_OPERATION_TYPE, &op_type);
239	    switch (op_type) {
240	        case SLAPI_OPERATION_MODIFY:
241	            dns = slapi_ldap_explode_dn(entry_dn, 0);
242	            if (dns == NULL) {
(gdb) break slapi_pblock_get
Breakpoint 2 at 0x3ff9cf43e00: file ldap/servers/slapd/pblock.c, line 373.
(gdb) c
(gdb) list
614	    case SLAPI_OPERATION_TYPE:
615	        if (pblock->pb_op == NULL) {
616	            slapi_log_err(SLAPI_LOG_ERR,
617	                          "slapi_pblock_get", "Operation is NULL and hence cannot access SLAPI_OPERATION_TYPE \n");
618	            return (-1);
619	        }
620	        (*(int *)value) = pblock->pb_op->o_params.operation_type;
621	        break;
(gdb) print pblock->pb_op->o_params
$3 = {operation_type = 8, target_address = {udn = 0x3ff83c0d080 "dc=example,dc=com", uniqueid = 0x0, sdn = 0x3ff83c25000}, csn = 0x0, request_controls = 0x0, p = {
    p_add = {target_entry = 0x3ff83c0d1e0, parentuniqueid = 0x0}, p_bind = {bind_method = 4395961995744, bind_creds = 0x0, bind_saslmechanism = 0x0, 
      bind_ret_saslcreds = 0x0}, p_compare = {compare_ava = {ava_type = 0x3ff83c0d1e0 "", ava_value = {bv_len = 0, bv_val = 0x0}, ava_private = 0x0}}, p_modify = {
      modify_mods = 0x3ff83c0d1e0}, p_modrdn = {modrdn_newrdn = 0x3ff83c0d1e0 "", modrdn_deloldrdn = 0, modrdn_newsuperior_address = {udn = 0x0, uniqueid = 0x0, 
        sdn = 0x0}, modrdn_mods = 0x0}, p_search = {search_scope = 1023, search_deref = -2084515360, search_sizelimit = 0, search_timelimit = 0, search_filter = 0x0, 
      search_strfilter = 0x0, search_attrs = 0x0, search_attrsonly = 0, search_is_and = 0, search_gerattrs = 0x0}, p_abandon = {abandon_targetmsgid = 1023}, p_extended = {
      exop_oid = 0x3ff83c0d1e0 "", exop_value = 0x0}}}
(gdb) whatis pblock->pb_op->o_params.operation_type
type = unsigned long

# in the pblock pblock->pb_op->o_params.operation_type is an unsigned long (8 bytes)
# the value SLAPI_OPERATION_MODIFY=8 is set in big endian form
# with 0x3ff9a6de50f = 0x08
(gdb) print &pblock->pb_op->o_params
$4 = (struct slapi_operation_parameters *) 0x3ff9a6de508
0x3ff9a6de508:	0x0000000000000008	0x000003ff83c0d080
0x3ff9a6de518:	0x0000000000000000	0x000003ff83c25000
(gdb) whatis pblock->pb_op->o_params.operation_type
type = unsigned long
(gdb) print sizeof(pblock->pb_op->o_params.operation_type)
$14 = 8

(gdb) x/bx 0x3ff9a6de508
0x3ff9a6de508:	0x00
(gdb) x/bx 0x3ff9a6de509
0x3ff9a6de509:	0x00
(gdb) x/bx 0x3ff9a6de50a
0x3ff9a6de50a:	0x00
(gdb) x/bx 0x3ff9a6de50b
0x3ff9a6de50b:	0x00
(gdb) x/bx 0x3ff9a6de50c
0x3ff9a6de50c:	0x00
(gdb) x/bx 0x3ff9a6de50d
0x3ff9a6de50d:	0x00
(gdb) x/bx 0x3ff9a6de50e
0x3ff9a6de50e:	0x00
(gdb) x/bx 0x3ff9a6de50f
0x3ff9a6de50f:	0x08

# value is a (void *) 8 bytes initialized to 0
(gdb) print value
$5 = (void *) 0x3ff866fc980
(gdb) x/1gz 0x3ff866fc980
0x3ff866fc980:	0x0000000000000000
(gdb) whatis value
type = void *
(gdb) print sizeof(value)
$12 = 8

# we should expect *value to be set to 
#	0x0000000000000008
# but it is set to
#	0x0000000800000000
(gdb) 
620	        (*(int *)value) = pblock->pb_op->o_params.operation_type;
(gdb) x/1gz 0x3ff866fc980
0x3ff866fc980:	0x0000000000000000
(gdb) x/1gz 0x3ff9a6de508
0x3ff9a6de508:	0x0000000000000008
(gdb) n
621	        break;
(gdb) x/1gz 0x3ff866fc980
0x3ff866fc980:	0x0000000800000000

</pre>

Looking at the instructions, it looks it is accessing the src as an 'int'

<pre>
# the instruction (*(int *)value) = pblock->pb_op->o_params.operation_type;
# is accessing pblock->pb_op->o_params.operation_type like a 'int' (4 bytes)
# not like a unsigned long (8 bytes)
#
# note: taken from another run where 
# (gdb) print &pblock->pb_op->o_params.operation_type
# $24 = (unsigned long *) 0x3ff9a6de908

(gdb) where
#0  slapi_pblock_get (pblock=pblock@entry=0x3ff80b02580, arg=arg@entry=590, value=value@entry=0x3ff815fc980) at ldap/servers/slapd/pblock.c:373
#1  0x000003ff96bdc950 in entry_get_rdn_mods (pb=pb@entry=0x3ff80b02580, entry=0x3ff80b51180, csn=0x0, repl_op=<optimized out>, smods_ret=smods_ret@entry=0x3ff815fcb90)
    at ldap/servers/slapd/back-ldbm/ldbm_modify.c:238
#2  0x000003ff96bdcfa8 in ldbm_back_modify (pb=0x3ff80b02580) at ldap/servers/slapd/back-ldbm/ldbm_modify.c:847
#3  0x000003ff9cf396f6 in op_shared_modify (pb=pb@entry=0x3ff80b02580, pw_change=pw_change@entry=0, old_pw=0x0) at ldap/servers/slapd/modify.c:1025
...
373         be = pblock->pb_backend;
(gdb) n
375         switch (arg) {
(gdb) n
615             if (pblock->pb_op == NULL) {
(gdb) n
620             (*(int *)value) = pblock->pb_op->o_params.operation_type;
(gdb) print $pc
$26 = (void (*)()) 0x3ff9cf44498 <slapi_pblock_get+1688>

(gdb) x/20i 0x3ff9cf44498
=> 0x3ff9cf44498 <slapi_pblock_get+1688>:       l       %r1,268(%r1)
   0x3ff9cf4449c <slapi_pblock_get+1692>:       lhi     %r2,0
   0x3ff9cf444a0 <slapi_pblock_get+1696>:       st      %r1,0(%r4)
   0x3ff9cf444a4 <slapi_pblock_get+1700>:       j       0x3ff9cf43e44 <slapi_pblock_get+68>
(gdb) print (void*)$r1
$22 = (void *) 0x3ff9a6de800
(gdb) print (void*)$r1+268
$23 = (void *) 0x3ff9a6de90c
(gdb) x/gz 0x3ff9a6de90c                <--- access 4 bytes shift vs &pblock->pb_op->o_params.operation_type
0x3ff9a6de90c:  0x00000008000003ff

(gdb) print &pblock->pb_op->o_params.operation_type
$24 = (unsigned long *) 0x3ff9a6de908
(gdb) x/1gz 0x3ff9a6de908
0x3ff9a6de908:  0x0000000000000008

</pre>

I have not a clear understanding of what is broken. However, it looks source and destination of a memory access are not aligned with the type of the source and destination.
From the code point of view, I see no issue. But with such behaviour, the current build of 389-ds on s390 is broken. This failure is very likely not the only one.

**Comment by tbordaz** [comment]
The regression was introduced in 1.4.3 (https://pagure.io/389-ds-base/issue/49859). setting milestone to 1.4.3

**Comment by tbordaz** [comment]
827773829..90c488370  master
9f9eb91e2..900e6fdcf  389-ds-base-1.4.4
263a87bc2..eed7abeb9  389-ds-base-1.4.3
