### ISSUE TITLE
ldif2ldap should support the '-y' option to read the password from a file

### ISSUE THREAD

**Issue by trevor-vaughan** [389ds/389-ds-base#4627]
To prevent the addition of passwords to the command line history and showing up in a process search, I would like `ldif2ldap` to support the underlying `-y` option so that the password may be input via a file.

**Comment by Firstyear** [comment]
@mreynolds389 I can't find ldif2ldap in the source, is this one of the deprecated/removed scripts that we recently removed in 2.x.x?

**Comment by progier389** [comment]
I doubt we will implement new feature on old obsolete tool  
But there is trivial work around that does not require password if ldapi is enabled: using new dsconf tools:

dsconf instanceName backend export -l ldifFile backendName

Another way adaptable to any interactive command is to write an "expect" script:

Here I put an example to export a ldif file based on more recent dsconf tools (because ldif2ldap is broken in my  environment):

$ cat myexport
#!/usr/bin/expect

set url [lindex $argv 0]
set backendName [lindex $argv 1]
set ldif [lindex $argv 2]

set dn "cn=directory manager"
set pwd "password"

spawn dsconf $url backend export -l $ldif $backendName

expect "Enter Bind DN: "
send "$dn\r";

expect "Enter password for $dn on $url: "
send "$pwd\r";

interact
# end of script

$ chmod 500 myexport

$ ./myexport ldaps://linux.home:5556 userRoot /tmp/db.ldif 
spawn dsconf ldaps://linux.home:5556 backend export -l /tmp/db.ldif userRoot
Enter Bind DN: cn=directory manager
Enter password for cn=directory manager on ldaps://linux.home:5556: 
The export task has finished successfully

$

**Comment by trevor-vaughan** [comment]
Fair enough. The tool wasn't earth shattering but the fallback mechanism was nice. Closing since the tool is obsolete.
