### ISSUE TITLE
dsconf for nsslapd-state

### ISSUE THREAD

**Issue by falon** [389ds/389-ds-base#4796]
**Is your feature request related to a problem? Please describe.**
With the old console on 389-ds 1.3.x I can manage the `nsslapd-state` for all suffixes.
In the new cockpit console I can't find an option to manage this attribute. It's always `backend`.
`dsconf ` doesn't manage this attribute too.

**Describe the solution you'd like**
At least, a new option in `dsconf `could be provided. For instance:

`dsconf instance backend suffix set --state`

Allowed values:

- `backend`: The back-end database processes all operations.
- `disabled`: The database is not available for processing operations. The server returns a No
such search object error in response to requests made by client applications.
- `referral`: Directory Server returns a referral URL for requests to this suffix.
- `referral on update`: The database is used for all operations. Only for update requests is a
referral sent.

**Describe alternatives you've considered**
Now I have to force an `ldapmodify `to set the value:

```
dn: cn=<suffix name>,cn=mapping tree,cn=config
changeype: modify
replace: nsslapd-state
nsslapd-state: referral on update
```

**Comment by mreynolds389** [comment]
This can definitely be added to the CLI and UI.  We are currently working on porting the UI to Patternfly 4 so this is a good time to add this change...

**Comment by progier389** [comment]
just a point about that one: by default  dsconf should not allow to change the state of a replicated backend. 
  (because replication sometimes overrides the state (and the referrals) and it will be confusing for user.
If we really want to offer the referral on update feature we also need to improve the ns-sate handling within the server 
  (for example by having 3 attributes:  ns-state (which is only readable and computed from nsstate;replica and ns-state;config)
   to insure there is no risk to revert in backend mode unexpectedly

**Comment by mreynolds389** [comment]
4634ec6ab..2e4387db6  389-ds-base-2.0 -> 389-ds-base-2.0

This will eventually be backported to 389-ds-base-1.4.4 as part of a UI/lib389 rebase.
