### ISSUE TITLE
Listener thread does not scale when dealing with a high number of established connections

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#4812]
**Issue Description**
Listener thread poll established connections. When the number of connections is high and/or there is a high incoming traffic, this single thread becomes a bottleneck. The thread is eating a lot of cpu to go through the huge array of established connection but it is not running fast enough if there is a big incoming traffic and finally limits the capacity of the server.

The idea is to split the connection table into several portions. Each portion being poll by a dedicated listener thread. 
This solution would also help to scale for 10K problem

**Package Version and Platform:**
 all version

**Steps to Reproduce**
Configure the server with a connection table with 5000 slots. Create 5000 clients and hammer the server. The overall throughput is lower than with 100 clients hammering the server (TBC)
One symptom would be high CPU on listener.

**Expected results**
High CPU should be on workers and throughput with large number of client should be higher than with smaller number of clients

**Comment by jchapma** [comment]
Design doc for review - https://github.com/mreynolds389/389wiki/pull/64

**Comment by tbordaz** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1975930

**Comment by progier389** [comment]
Hi @jchapma
 I am afraid that there is a regression with latest commit ! 
Instance creation fails on ASAN build (server fails to start)
Problem is due to a buffer overflow 
#0  __sanitizer::Die () at ../../../../libsanitizer/sanitizer_common/sanitizer_termination.cpp:50
#1  0x00007ffff7694dbc in __asan::ScopedInErrorReport::~ScopedInErrorReport (this=0x7fffffffb8a6, __in_chrg=<optimized out>) at ../../../../libsanitizer/asan/asan_report.cpp:190
#2  0x00007ffff7694686 in __asan::ReportGenericError (pc=4364047, bp=bp@entry=140737488340240, sp=sp@entry=140737488340232, addr=108095737118976, is_write=is_write@entry=true, access_size=access_size@entry=8, exp=0, fatal=true) at ../../../../libsanitizer/asan/asan_report.cpp:478
#3  0x00007ffff769563f in __asan::__asan_report_store8 (addr=<optimized out>) at ../../../../libsanitizer/asan/asan_rtl.cpp:126
#4  0x000000000042970f in connection_table_new (table_size=table_size@entry=1024) at /home/progier/sb/ai1/tst/source/389-ds-base/ldap/servers/slapd/conntable.c:198
#5  0x00000000004337bd in slapd_daemon (ports=ports@entry=0x7fffffffcf60) at /home/progier/sb/ai1/tst/source/389-ds-base/ldap/servers/slapd/daemon.c:931
#6  0x0000000000448619 in main (argc=<optimized out>, argv=<optimized out>) at /home/progier/sb/ai1/tst/source/389-ds-base/ldap/servers/slapd/main.c:1131
(gdb) up 4
#4  0x000000000042970f in connection_table_new (table_size=table_size@entry=1024) at /home/progier/sb/ai1/tst/source/389-ds-base/ldap/servers/slapd/conntable.c:198
198	            ct->c_freelist[free_idx++] = &(ct->c[ct_list][i]);
(gdb) p ct->c_freelist
$1 = (Connection **) 0x625000032100
(gdb) p ct->size
$2 = 1024
(gdb) p i
$3 = 1024
(gdb) p ct->list_size
$4 = 1025
(gdb) p free_idx
$5 = 1025
(gdb) p ct->size
$6 = 1024

Note: free_idx is 1024 when the overflow occurs (according to the overflow address and to the fact that free_list has 1024 element)
I will patch my build to alloc ct->size+1 element in the free list  and be able to work but I will let you fix thing properly

**Comment by jchapma** [comment]
@progier389 
I can reproduce this issue with an asan build, im confused as to why I never hit this issue during testing. All my machines have been configured for a large number of file descriptors,  which might "hide" the issue. I will fix this first thing in the morning. Thanks

**Comment by droideck** [comment]
Also, the resent failures in tests have started because of the commit https://github.com/389ds/389-ds-base/commit/489b585a67bf9b91c33a93cf8b0c6c7bca398bee

I've tried to revert it and the tests pass without issues.

**Comment by mreynolds389** [comment]
@jchapma - your latest commit is triggering an error in the logs about a zero alloc attempt at server start up.  This needs to be fixed as it could potentially cause other issues that we haven't hit yet:

```
[20/Mar/2023:14:44:40.707959412 -0400] - ERR - memory allocator - cannot calloc 0 bytes;
trying to allocate 0 or a negative number of bytes is not portable and
gives different results on different platforms.


#0  log_negative_alloc_msg (size=0, units=0x7ffff7ea8595 "bytes", op=0x7ffff7ea8654 "calloc") at ../389-ds-base/ldap/servers/slapd/ch_malloc.c:75
#1  slapi_ch_calloc (nelem=nelem@entry=1, size=0) at ../389-ds-base/ldap/servers/slapd/ch_malloc.c:166
#2  0x000000000041dce8 in connection_table_new (table_size=63936) at ../389-ds-base/ldap/servers/slapd/conntable.c:132
#3  slapd_daemon (ports=0x7fffffffdb50) at ../389-ds-base/ldap/servers/slapd/daemon.c:932
#4  0x00000000004136c6 in main (argc=9, argv=0x7fffffffdf88) at ../389-ds-base/ldap/servers/slapd/main.c:1132
```

**Comment by vashirov** [comment]
@jchapma, is there anything else needs to be done for this issue? Can we close it?

**Comment by jchapma** [comment]
> @jchapma, is there anything else needs to be done for this issue? Can we close it?

Yes this issue is resolved, I will close it. Thanks
