### ISSUE TITLE
Potential deadlock error due to the re-acquisition to the same lock

### ISSUE THREAD

**Issue by jenny-cheung** [389ds/389-ds-base#4836]
Dear Developers:
                First, thank you for your checking. It seems that there is an error due to the two lock statement  `pthread_mutex_lock(&notify_lock);` in the function` check_replicas_are_done_cleaning(cleanruv_data *data)` . Should the second one be the unlock statement `pthread_mutex_unlock(&notify_lock);`.

https://github.com/389ds/389-ds-base/blob/4559a89c0877e45143fa3c9cc34393d4d0cd2696/ldap/servers/plugins/replication/repl5_replica_config.c#L2197

https://github.com/389ds/389-ds-base/blob/4559a89c0877e45143fa3c9cc34393d4d0cd2696/ldap/servers/plugins/replication/repl5_replica_config.c#L2199

```
static void
check_replicas_are_done_cleaning(cleanruv_data *data)
{
    ...;

        cleanruv_log(data->task, data->rid, CLEANALLRUV_ID, SLAPI_LOG_NOTICE,
                     "Not all replicas finished cleaning, retrying in %d seconds",
                     interval);
        if (!slapi_is_shutting_down()) {
            struct timespec current_time = {0};
            clock_gettime(CLOCK_MONOTONIC, &current_time);
            current_time.tv_sec += interval;
            pthread_mutex_lock(&notify_lock);  // first time 
            pthread_cond_timedwait(&notify_cvar, &notify_lock, &current_time);
            pthread_mutex_lock(&notify_lock);  //second time
        }

        interval *= 2;
        if (interval >= CLEANALLRUV_MAX_WAIT) {
            interval = CLEANALLRUV_MAX_WAIT;
        }
    }
    slapi_ch_free_string(&filter);
}
```

**Comment by jenny-cheung** [comment]
Hi, developers @mreynolds389 @jchapma @Firstyear 

Any comments would be highly appreciated. Thank you.

Best Regards,

**Comment by jenny-cheung** [comment]
Hi, developers @mreynolds389 @jchapma @Firstyear 

Any comments would be highly appreciated. Thank you.

Best Regards,

**Comment by Firstyear** [comment]
Sorry for the delay @jenny-cheung. I think you are correct here. Other uses point to a lock/timedwait/unlock usage such as https://github.com/389ds/389-ds-base/blob/4559a89c0877e45143fa3c9cc34393d4d0cd2696/ldap/servers/plugins/replication/repl5_replica_config.c#L2308  As well reading man 3 pthread_cond_timedwait it says "Upon successful return, the mutex shall have been locked and shall be owned by the calling thread.". Which means that indeed here on the second attempt because this is not a recursive mutex then a deadlock will occur.

Since it's a small change please feel free to create a PR with the fix for us to review :) Alternately, I'm happy to do the PR for you if you prefer.

Thank you very much for the report!

**Comment by jenny-cheung** [comment]
Thank you for your detailed reply! I have created a PR for this. Please check.
