### ISSUE TITLE
OpenLDAP is not shipped with non-threaded version of libldap

### ISSUE THREAD

**Issue by droideck** [389ds/389-ds-base#5032]
**Issue Description**
389-ds-base is built with libldap_r shared library. The non-threaded version of libldap is fully depricated since Fedora 34, libldap_r supplied as symlinks. OpenLDAP 2.6 won't have libldap_r at all. Hence, we should rewrite our Makefile.

**Comment by mreynolds389** [comment]
Should this be cherry-picked to earlier versions?

**Comment by droideck** [comment]
> Should this be cherry-picked to earlier versions?

It should be present only in Fedora 36 Rawhide because the OpenLDAP 2.6 release should happen not early than that. So I think it should not be cherry-picked.

**Comment by mreynolds389** [comment]
> > Should this be cherry-picked to earlier versions?
> 
> It should be present only in Fedora 36 Rawhide because the OpenLDAP 2.6 release should happen not early than that. So I think it should not be cherry-picked.

Just checking - thanks!

**Comment by mreynolds389** [comment]
> @droideck, @mreynolds389, any chance to see the fixes on 1.4.3 branch?

@droideck I thought you said this should NOT be put into earlier versions.  Looks like its not backported because it conflicts with openldap versions less than 2.6.  Can you clarify this for @stanislavlevin ? 

FYI 389-ds-base-1.4.3 is no longer supported upstream (it's only used for maintenance releases on RHEL 8), so we can not commit any changes that will break RHEL 8, but lets wait for @droideck first.  Of course you can always fork the project and do your own builds for whatever platform you are using if we can not backport it.

**Comment by stanislavlevin** [comment]
> FYI 389-ds-base-1.4.3 is no longer supported upstream (it's only used for maintenance releases on RHEL 8), so we can not commit any changes that will break RHEL 8, but lets wait for @droideck first.

@mreynolds389,
thanks for the information! I was periodically asking on the maillist about supported branches and asked to inform maintainers from downstream ;) So, which ones are supported atm?

@tjaalton, ^

> Of course you can always fork the project and do your own builds for whatever platform you are using if we can not backport it.

Yes, I can. But I thought somebody else uses that branch in downstream and they may want/have to switch to openldap 2.6+.

**Comment by mreynolds389** [comment]
Yeah it's an odd situation.  Really we are only supporting (upstream) 389-ds-base-2.0 and up.  Downstream (RHEL) we use 1.4.3 for all RHEL 8 releases (RHEL 8 is sort of wrapping up now), and 389-ds-base-2.x is used for RHEL 9.  389-ds-base-3.x will be for next major version of RHEL, etc.

Note 1.4.4 sort of just became "lost/abandoned".  Long story, but I messed that branch up with the timing of RHEL releases, and it was basically abandoned. 

Now I just checked, openldap 2.6 is not officially available in RHEL 8 (no plans to do so either), which is why I'm assuming this issue can not be backported to 1.4.3. Again @droideck is way more familiar with this than I am, but he is out sick today.  I'm sure he'll follow up tomorrow if he returns to work.

Since our upstream releases/branches are closely tied to RHEL you can follow the RHEL support cycle to know what we officially support.  So 1.4.3 will be around for all of RHEL 8 (but there are no upstream builds anymore and whatever we do with this branch must be compatible with RHEL 8), and then 2.x will be for all of RHEL 9.  

Upstream builds follow the Fedora release schedule.  So on Fedora we will support and do builds as follows:

Fedora 35 --> 389-ds-base-2.0  --> RHEL 9.0
Fedora 36 --> 389-ds-base-2.1  --> RHEL 9.1
Fedora 37 --> 389-ds-base-2.2  --> RHEL 9.2
...

Once Fedora 35 EOLs then upstream builds will obviously stop for 389-ds-base-2.0.  That branch will still receive updates, but again they must be compatible with RHEL 9.0, etc.

**Comment by Firstyear** [comment]
> Note 1.4.4 sort of just became "lost/abandoned". Long story, but I messed that branch up with the timing of RHEL releases, and it was basically abandoned.

https://github.com/Firstyear/389-ds-base/tree/389-ds-base-1.4.4-suse-sp3

We maintain this branch since it happened to end up in a SLE release. But SP3 is not our primary target, and we have moved to 2.0 in SP4, so generally I take care of CVE backports as needed for SUSE.

**Comment by stanislavlevin** [comment]
> Yeah it's an odd situation. Really we are only supporting (upstream) 389-ds-base-2.0 and up. Downstream (RHEL) we use 1.4.3 for all RHEL 8 releases (RHEL 8 is sort of wrapping up now), and 389-ds-base-2.x is used for RHEL 9. 389-ds-base-3.x will be for next major version of RHEL, etc.
> 
> Note 1.4.4 sort of just became "lost/abandoned". Long story, but I messed that branch up with the timing of RHEL releases, and it was basically abandoned.
> 
> Now I just checked, openldap 2.6 is not officially available in RHEL 8 (no plans to do so either), which is why I'm assuming this issue can not be backported to 1.4.3. Again @droideck is way more familiar with this than I am, but he is out sick today. I'm sure he'll follow up tomorrow if he returns to work.
> 
> Since our upstream releases/branches are closely tied to RHEL you can follow the RHEL support cycle to know what we officially support. So 1.4.3 will be around for all of RHEL 8 (but there are no upstream builds anymore and whatever we do with this branch must be compatible with RHEL 8), and then 2.x will be for all of RHEL 9.
> 
> Upstream builds follow the Fedora release schedule. So on Fedora we will support and do builds as follows:
> 
> Fedora 35 --> 389-ds-base-2.0 --> RHEL 9.0 Fedora 36 --> 389-ds-base-2.1 --> RHEL 9.1 Fedora 37 --> 389-ds-base-2.2 --> RHEL 9.2 ...
> 
> Once Fedora 35 EOLs then upstream builds will obviously stop for 389-ds-base-2.0. That branch will still receive updates, but again they must be compatible with RHEL 9.0, etc.

Many thanks for excellent clarification! Bookmarked :)

**Comment by droideck** [comment]
Yep, that

> Yeah it's an odd situation. Really we are only supporting (upstream) 389-ds-base-2.0 and up. Downstream (RHEL) we use 1.4.3 for all RHEL 8 releases (RHEL 8 is sort of wrapping up now), and 389-ds-base-2.x is used for RHEL 9. 389-ds-base-3.x will be for next major version of RHEL, etc.
> 
> Note 1.4.4 sort of just became "lost/abandoned". Long story, but I messed that branch up with the timing of RHEL releases, and it was basically abandoned.
> 
> Now I just checked, openldap 2.6 is not officially available in RHEL 8 (no plans to do so either), which is why I'm assuming this issue can not be backported to 1.4.3. Again @droideck is way more familiar with this than I am, but he is out sick today. I'm sure he'll follow up tomorrow if he returns to work.

That's 100% correct! There are no plans to support OpenLDAP 2.6 in 1.4.3 or 1.4.4.
So we are good here.

We still need to deal with https://github.com/389ds/389-ds-base/issues/5339 though.
So we'll need to adopt the 1.4.3 branch to be able to build with the system where OpenLDAP 2.6 is installed. But it's not official support by any means, and it will be used only for our CI test runs.
