### ISSUE TITLE
in OpenQA changelog trimming can crashes

### ISSUE THREAD

**Issue by abbra** [389ds/389-ds-base#5037]
OpenQA shows that a replica deployment crashes in https://openqa.fedoraproject.org/tests/1071548#step/realmd_join_sssd/33

I am attaching logs which also can be found in a "Logs & Assets" tab at the link above.

There is a crash and then AVCs when systemd-coredump attempts to create a stack trace. AVCs are post crash, not a reason for crash.

Package version: 389-ds-base-2.0.11-1.fc36

Fedora bug with logs and coredumps: https://bugzilla.redhat.com/show_bug.cgi?id=2026980

I suspect it is because there is no check for NULL of cldb in cl5TrimMain():

static int
_cl5TrimMain(void *param)
{
    struct timespec current_time = {0};
    struct timespec prev_time = {0};
    Replica *replica = (Replica *)param;
    cldb_Handle *cldb = replica_get_cl_info(replica);
    int32_t trimInterval = cldb->clConf.trimInterval;

    /* Get the initial current time for checking the trim interval */
    clock_gettime(CLOCK_MONOTONIC, &prev_time);

    /* Lock the CL state, and bump the thread count */
    pthread_mutex_lock(&(cldb->stLock));
    slapi_counter_increment(cldb->clThreads);

    while (cldb->dbState == CL5_STATE_OPEN)
    {
        pthread_mutex_unlock(&(cldb->stLock));

        clock_gettime(CLOCK_MONOTONIC, &current_time);
        if (current_time.tv_sec - prev_time.tv_sec >= trimInterval) {
            /* time to trim */
            prev_time = current_time;
            _cl5TrimReplica(replica);
        }

        pthread_mutex_lock(&(cldb->clLock));
        /* While we have the CL lock get a fresh copy of the trim interval */
        trimInterval = cldb->clConf.trimInterval;
        current_time.tv_sec += trimInterval;
        pthread_cond_timedwait(&(cldb->clCvar), &(cldb->clLock), &current_time);
        pthread_mutex_unlock(&(cldb->clLock));

        pthread_mutex_lock(&(cldb->stLock));
    }
    slapi_counter_decrement(cldb->clThreads);

    pthread_mutex_unlock(&(cldb->stLock));

    return 0;
}

where 

void *
replica_get_cl_info(Replica *r)
{
    return r ? r->cldb : NULL;
}

so if r->cldb is NULL, we'd crash on trimInterval initialization.

**Comment by tbordaz** [comment]
The crash occurs because the replica has no changelog. changelog is dereferenced without tests

<pre>
2175	_cl5TrimMain(void *param)
2176	{
2177	    struct timespec current_time = {0};
2178	    struct timespec prev_time = {0};
2179	    Replica *replica = (Replica *)param;
2180	    cldb_Handle *cldb = replica_get_cl_info(replica);
2181	    int32_t trimInterval = cldb->clConf.trimInterval;   <<<--- Here
</pre>

It is not yet clear if the crash is dynamic or not because at the same time Thread 30 was doing an import and Thread 16 was ending an import.
Anyway the fix is a oneline fix

**Comment by tbordaz** [comment]
ATM the easy fix in _cl5TrimMain is likely not the final fix as there may be an underlying race condition between 2 imports

**Comment by tbordaz** [comment]
The original issue (crash) does not exist in 1.4.3 that is using a common s_cl5Desc variable instead of a per replica cldb.
The second part if the patch, preventing multiple trimming threads, address a rare case and do not justify a backport.

d02054dc6..97119ebed  master
37049b3ad..d051255a1  389-ds-base-2.0
7af2eb9ff..0ebb39e05  389-ds-base-1.4.4
