### ISSUE TITLE
Winsync fromAD preserve the tree structure of Active Directory

### ISSUE THREAD

**Issue by rainolf** [389ds/389-ds-base#5051]
Hi,
doing a OneWay replication with WinSync It looks like 389 tries to preserve the tree structure of AD, when it's probably
actually not needed because of AD's always-unique RDN policy.
If OUs are not defined in destination D389 the replication will fails.

**Comment by Firstyear** [comment]
I think the best way to proceed here is a setting on the agreement that directs 389 to flatten the AD structure. This is safe because AD enforces unique RDN's in the the tree, meaning that we'll never have a conflict case. This setting would be OFF by default since it would change the behaviour of AD sync quite considerably. 

@mreynolds389 @tbordaz thoughts? I'm happy to do the work on this, just want you know know I plan to do it.
