### ISSUE TITLE
389-ds crashes in FreeIPA Azure CI

### ISSUE THREAD

**Issue by abbra** [389ds/389-ds-base#5199]
When running FreeIPA CI in Azure, we've got a crash in 389-ds under memory pressure. I am attaching a tarball of the content, including coredump, stacktrace, and logs of the test runs.

[logs-GATING.upgrade_1_to_1-10600-2-2-6-Linux-X64.zip](https://github.com/389ds/389-ds-base/files/8247374/logs-GATING.upgrade_1_to_1-10600-2-2-6-Linux-X64.zip)

**Comment by abbra** [comment]
The run 10600 itself has more artifacts here: https://dev.azure.com/freeipa/freeipa/_build/results?buildId=10600&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Firstyear** [comment]
The crash is here:

#0  sync_refresh_initial_content (pb=pb@entry=0x7f38bd3fc580,
    sync_persist=sync_persist@entry=0, tid=tid@entry=0x0, sc=0x0)
    at ldap/servers/plugins/sync/sync_refresh.c:413
413         if (sc->openldap_compat == PR_TRUE) {

Makes me think that `sync_cookie_create(Slapi_PBlock *pb, Sync_Cookie *client_cookie)` from sync_util.c failed to allocate, and since it was an initial sync there was no attempt to write to sc because client_cookie would have been null. What's weird is slapi_ch_calloc should be triggering exit(1) as a result because of the returned null pointer, and there are no writes to session_cookie that I can see between the alloc and refresh. 

We can certainly try to harden this part of the code, but in low memory conditions, there is nothing we can do in this situation beside trying to fail more gracefully. Trying to run FreeIPA in 2GB of ram seems like you are asking for disaster given how memory hungry many of the components of FreeIPA are. 

So I'm honestly not sure what the outcome is you want to see here. When you are low on memory, things will go sideways fast, because of the way that linux overcommits memory (linux will always return a valid pointer from malloc/calloc, and then ondemand map through the page table on first write, else the reads go to the shared null page), and that makes your whole system and applications more unstable, and prone to SIGSEGV due to inability to map pages, or at risk of OOM. My thinking is that you may have encountered some of this weirdness here. You could try to disable vm_overcommit to detect these bugs faster, but that has other joys associated with it. 

IMO this isn't really a bug we can do much about beside trying to detect this and shutdown gracefully.

**Comment by abbra** [comment]
I agree, I reported this because our automated test system detects crashes in containers and produces coredump/stacktrace to investigate. This is not the first time where a memory pressure of running multiple containers on the Azure CI host (with 6GB+6GB RAM+swap) is a bit tight to 4-5 containers of FreeIPA servers and clients.

Feel free to close if you think there is nothing to improve on 389-ds side.

**Comment by Firstyear** [comment]
> Makes me think that `sync_cookie_create(Slapi_PBlock *pb, Sync_Cookie *client_cookie)` from sync_util.c failed to allocate, and since it was an initial sync there was no attempt to write to sc because client_cookie would have been null. What's weird is slapi_ch_calloc should be triggering exit(1) as a result because of the returned null pointer, and there are no writes to session_cookie that I can see between the alloc and refresh.

I think in hindsight that with overcommit, the returned pointer will always be valid, but then if a page is failed to be returned from the page table, then it would cause the SEGV, which correlates to this. 

> I agree, I reported this because our automated test system detects crashes in containers and produces coredump/stacktrace to investigate. This is not the first time where a memory pressure of running multiple containers on the Azure CI host (with 6GB+6GB RAM+swap) is a bit tight to 4-5 containers of FreeIPA servers and clients.
> 
> Feel free to close if you think there is nothing to improve on 389-ds side.

I don't think there is much we can do when we are under such extreme memory pressure, when there is a lot of memory pressure also occurring from other parts of freeipa. IMO the reality is that FreeIPA just needs more ram. 

I'll leave it for @mreynolds389 to take a look, but I think there is nothing we can do to fix this.

**Comment by progier389** [comment]
I agree with @firstyear, there is not much we can do here.
 ( The only idea that came in mind would be  to trap the SEGV to exit gracefully, but IMHO the  drawbacks (not being ableto debug real issue) will be worse than the benefit.)
So let's close this issue ...
