### ISSUE TITLE
high contention in find_entry_internal_dn on mixed load

### ISSUE THREAD

**Issue by tbordaz** [389ds/389-ds-base#5262]
**Issue Description**
Under mixed load (updates and indexed searches), the pressure on the entry cache is so high that during an update by the time the entry is added into the cache,  it is then removed from the cache before it is locked for the update.
If such event occurs 1000 times in a raw, the update fails.

**Package Version and Platform:**
all versions

**Steps to Reproduce**
Was not able to reproduce

**Expected results**
Should not see messages like "Retry count exceeded"

**Screenshots**

**Additional context**

**Comment by tbordaz** [comment]
Reverting #4324 (https://github.com/389ds/389-ds-base/commit/abb93243b427ee122a5a80ed095c0118d7b6616e) prevent that lookup-lock fails 1000 times in a raw (msg 'Retry count exceeded').

#4324 improves performance for search (~8%)
It was not tested for write. This should be a first test to confirm there is no regression on write.

A second phase would be to implement an atomic lookup-lock

**Comment by tbordaz** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=2051476

**Comment by Firstyear** [comment]
The problem is that as we go to LMDB we will be moving to a concurrently readable transactional model. Having a "lock around the entry cache" basicly nerfs any performance gain from LMDB, and if we moved to a parallel hashmap, then we break our transactional guarantees. 

There are already transactional, concurrently readable caches that exist for exactly this scenario. I specifically wrote and designed one for the future use of 389-ds ( https://github.com/kanidm/concread/blob/master/CACHE.md , https://docs.rs/concread/latest/concread/arcache/index.html ) which you probably could consider.

**Comment by droideck** [comment]
Associated PR and an issue:
https://github.com/389ds/389-ds-base/pull/5463
https://github.com/389ds/389-ds-base/issues/4324

**Comment by tbordaz** [comment]
1011ad1fd..810fc8775 main
21314ec9e..3cc5e3829  389-ds-base-2.2
6c95604f6..00f5cd25d  389-ds-base-2.1
7ba233bf7..8d7d19faf  389-ds-base-2.0
8564399c5..1312c2796  389-ds-base-1.4.4
6d5537900..2a6870bcc  389-ds-base-1.4.3
