### ISSUE TITLE
DS fails to start in F36 containers

### ISSUE THREAD

**Issue by ckelleyRH** [389ds/389-ds-base#5317]
**Issue Description**
The PKI CI is now repeatedly failing as DS will not start in an F36 container. Example: https://github.com/dogtagpki/pki/pull/4009

**Package Version and Platform:**
 - Platform: **Fedora 36 container**
 - Package and version: **389-ds-base-2.1.1-1.fc36.x86_64** 
 - Browser **N/A**

**Steps to Reproduce**
1. Run PKI CI and observe failures, like the one mentioned above.

**Expected results**
DS should start in an F36 container.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by vashirov** [comment]
It fails because `setfacl` is missing. It's part of `acl` package and it's a dependency of 389-ds-base: https://src.fedoraproject.org/rpms/389-ds-base/blob/f36/f/389-ds-base.spec#_237
The version you have should pull this dependency. 
What is you Containerfile/Dockerfile? Or what's the container image that you use?

**Comment by vashirov** [comment]
Ah, ignore my last comment. The fix is the spec file, but there is no build that contains the fix. I'll kick off a new one.

**Comment by vashirov** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2022-c62ebaacc1

**Comment by vashirov** [comment]
Package update was pushed to stable, closing.
