### ISSUE TITLE
Allow selected users to perform fully unindexed searches 

### ISSUE THREAD

**Issue by Dzordzu** [389ds/389-ds-base#5318]
**Is your feature request related to a problem? Please describe.**
Currently only Directory Manager is allowed to perform unindexed search. It would be a nice feature to have a RO user that will be allowed to do such a thing

**Describe the solution you'd like**
Create a new attribute that can be attched to bind user. It should allow that user to perform unindexed search

**Describe alternatives you've considered**
Using a Directory Manager 

**Additional context**
It would be userful for backup user for external software

**Comment by mreynolds389** [comment]
This could probably be added to the per entry "resource limits" feature:

https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html/administration_guide/ldapsearch-ex-complex-range#Setting_Resource_Limits_Based_on_the_Bind_DN-Setting_Resource_Limits_Using_the_Command_Line

**Comment by Firstyear** [comment]
@Dzordzu The issue here is that even if you limit it to a subset of users, during the un-indexed search you are "blocking" and slowing down other searches due to the way things work in the backend. 

So the right answer is "index your search", not "allow un-indexed searches". Even if you partially index it, that's okay!

Is there a reason you can't index this search? What's prevnting you from this?

**Comment by Dzordzu** [comment]
LDAP is indexed. But the issue is within the request without filter. I want this feature (as I said before) mainly for backups.

**Comment by Firstyear** [comment]
But you don't need to do un-inedxed searches for backups. You'd use the 389-ds backup tools that can run online and do this properly.

What are you trying to achieve here?

**Comment by Dzordzu** [comment]
I'm using a bareos to perform backups. It contains an official LDAP plugin

**Comment by Firstyear** [comment]
What do you mean by "bareos" and "official LDAP plugin" here? I still think this approach to backups is likely wrong, and will probably not be viable to restore from in a real disaster scenario, due to missing replication metadata and other things. You should be using the inbuilt 389-ds backup tools which capture this information.

**Comment by Dzordzu** [comment]
By bareos i mean [bareos](https://www.bareos.com/download). By official LDAP plugin I mean [official LDAP plugin](https://docs.bareos.org/TasksAndConcepts/Plugins.html#ldap-plugin). We don't care about replication metadata. We want to keep things simple

**Comment by Firstyear** [comment]
>  I don't care much about replication metadata. I want to keep things simple

By trying to keep things simple, you are very likely to actually break things and cause more issues during a DR scenario. There are good reasons for why we recommend db2ldif or db2bak. Why not trigger a db2ldif and then backup the resulting content from ` /var/lib/dirsrv/slapd-<instance name>/ldif/ ` ?  Why are you trying to avoid our recommended and tested backup solutions? 

@mreynolds389 I think we can close this, since it's not a feature we really need, I think the answer is generally "index the missing attributes" or "what are you trying to achieve", and generally allowing a fully unindexed search like this is wrong.

**Comment by Dzordzu** [comment]
> EDIT: It looks like the bareos ldap plugin is also deprecated, which means it will likely go away in the future, which further supports that you should probably adjust your backup strategy.

It's deprecated, because of the python2 dependency which will be fixed in the following release

I understand your unwillingness towards this way of backuping ldap, but it's more universal way. I'll close the issue

**Comment by Firstyear** [comment]
> I understand your unwillingness towards this way of backuping ldap, but it's more universal way. I'll close the issue

It's not a more universal way. We want our users to know when they take a backup, that it will *work* when they need it most, during a disaster. Backup and restore are critical pieces of any disaster plan, and this approach won't work. 

So again, I'd encourage you to investigate db2ldif / db2bak, and then using bareos to capture the output as it exists in /var/lib/dirsrv.
