### ISSUE TITLE
RFE - Create a Security Audit Log

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5335]
Create a new server log that records "security" events:

- Authentication attacks
- Authorization issues
- DOS/TCP attacks
- etc

See this design doc for more details:

https://www.port389.org/docs/389ds/design/security-audit-log-design.html

Bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=2093981

**Comment by progier389** [comment]
> Other “high profile” accounts, how to specify them (multi-valued config attribute?

 I do not like too much the multi valued config idea
  because that means a somewhat costly lookup as we need to normalize the dns to compare the values
  I would rather add an auxilliary objectclass and an optional attribute to the entries
  since the entry is read during the authentication, cgecking the attribute would not be very costly ...
  (directory manager is an exception as there is no associated entry ... )
 That said it is a personal point of view and arguable ! -;)

Log format: 
  utc_time should be a floating number (i.e: 168485945.828151054) if you plan to use it as sorting key.

**Comment by mreynolds389** [comment]
@progier389 - this is still very much a rough draft at that stage (I was just throwing out ideas in the doc).  Thanks for your comments, I'll update the design doc soon.

**Comment by Firstyear** [comment]
The high profile account thing also can be "future" since any external log consumption system can apply that information
