### ISSUE TITLE
Only allow one fixup task at a time

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5413]
**Issue Description**

We keep seeing issues where customers incorrectly create 100's or 1000's of memberOf fixup tasks which leads to overall terrible server performance.  We should only allow one fixup task per plugin.

**Comment by mreynolds389** [comment]
198d921ca..fc205ec7c  389-ds-base-2.2 -> 389-ds-base-2.2
814f8b583..d1b16781e  389-ds-base-2.1 -> 389-ds-base-2.1
6083fd136..4401b66ca  389-ds-base-2.0 -> 389-ds-base-2.0
e665ae06a..5dd7043b3  389-ds-base-1.4.3 -> 389-ds-base-1.4.3

**Comment by tbordaz** [comment]
The detection of concurrent memberof task should be done consider base/filter.
IPA is doing valid parallel fixup tasks

<pre>
dn: cn=Update PBAC memberOf $TIME, cn=memberof task, cn=tasks, cn=config
objectClass: top
objectClass: extensibleObject
cn: IPA PBAC memberOf $TIME
basedn: cn=privileges,cn=pbac,$SUFFIX
filter: (objectclass=*)
ttl: 10

dn: cn=Update Role memberOf $TIME, cn=memberof task, cn=tasks, cn=config
objectClass: top
objectClass: extensibleObject
cn: Update Role memberOf $TIME
basedn: cn=roles,cn=accounts,$SUFFIX
filter: (objectclass=*)
ttl: 10
</pre>

**Comment by Firstyear** [comment]
This may not be true @tbordaz because IPA has nested groups. so you could have cn=some_priv,cn=privileges,cn=pbac,$SUFFIX which includes a member cn=myrole,cn=roles,cn=accounts,$SUFFIX. Since these are nested, this would trigger the members of cn=myrole to be adjusted too. Since there is *also* the second fixup in update role, it could conflict on the changes and cause loss of member of records.

I think that nested groups pretty much means you have to consider only one memberof fixup at a time.

**Comment by tbordaz** [comment]
I absolutely agree with your point. With nested groups it is unpredictable if parallel fixup will or not steps on each other. In addition I would say that parallel fixup will increase DB pressure (even if accessing different entries) with a higher risk of retries so from performance pov, there is a possibility that parallel fixups will take more time that serialized one.

Now IMHO it should be in the hand of the administrators/applications to decide/experiment if parallel fixups bring some benefits.

This ticket was initially created because of an administrator launched multiple times **by mistake** the exact same fixup. So I would rather see this ticket to prevent same base/filter tasks.

**Comment by mreynolds389** [comment]
Well the real issue I was trying to prevent was allowing "identical" tasks to be run at the same time.   But there are legitimate cases where you might want to fixup tasks two different branches.  Refining fix...

**Comment by mreynolds389** [comment]
216c14d62..1091ca9b5  389-ds-base-2.2 -> 389-ds-base-2.2
36e32f4d1..9d086f436  389-ds-base-2.1 -> 389-ds-base-2.1
959d36e6e..70e0175ea  389-ds-base-2.0 -> 389-ds-base-2.0
08ce159c0..90a83192d  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
