### ISSUE TITLE
CI - harden web UI tests

### ISSUE THREAD

**Issue by mreynolds389** [389ds/389-ds-base#5599]
**Issue Description**

  The web UI tests random fail.  These tests should be more robust

**Comment by mreynolds389** [comment]
b449e7d91..1b5d136fa  389-ds-base-2.2 -> 389-ds-base-2.2
a1df37a8f..4dfb91b1a  389-ds-base-2.1 -> 389-ds-base-2.1

**Comment by droideck** [comment]
I wonder if we can use something native for playwright lib instead of sleep.
I found a few options here: https://chercher.tech/python-playwright/waits-timeouts-playright-python

IMO, the best bet will be to use `wait_for_selector` which waits for an element to be present on the page. I may take a look later, mostly as a new lib practice :)
