### ISSUE TITLE
Default ldif filename for ldfigen shouldn't be in /tmp

### ISSUE THREAD

**Issue by vashirov** [389ds/389-ds-base#5667]
**Issue Description**
`ldifgen` uses `/tmp/ldifgen.ldif` for all subcommands except for `users` and `nested`.
```
 --ldif-file LDIF_FILE
                        The LDIF file name. Default is "/tmp/ldifgen.ldif"
```
`/tmp` is a bad default because dirsrv service has `PrivateTmp=on` and ldif files from system `/tmp` can't be loaded.
`users` and `nested` use instance's ldif directory: 
```
  --ldif-file LDIF_FILE
                        The LDIF file name. Default location is the server's
                        LDIF directory using the name 'users.ldif'
```
It would be good to use the same for the rest of the subcommands.

**Package Version and Platform:**
 - Platform: RHEL and Fedora
 - Package and version: 389-ds-base-1.4.3.32+

**Comment by mreynolds389** [comment]
This was by design.  Like a modification and COS ldifs are only added by ldapmodify.  If it's not an LDIF that needs to be imported then it doesn't "need" to be in the servers ldif directory.  Personally I find it very convenient if I have to run ldapmodify to not have to type out a long path for the ldif file.  But the user can always set whatever path they want - I was just trying to make it easier on me since I use this tool a lot :-)

So I guess I'll use one default path then... ;-)

**Comment by vashirov** [comment]
I needed to generate some users and groups and then import them using `ldif2db`, so I was a bit surprised by the inconsistency in the subcommands. But your use case makes sense too. And since it's possible to specify any location, it should cover `ldapmodify` case too, just longer to type :)

**Comment by mreynolds389** [comment]
c6613be07..fa344b9e9  389-ds-base-2.2 -> 389-ds-base-2.2
5f5150277..c58c5d14a  389-ds-base-2.1 -> 389-ds-base-2.1
332e4872f..3242ae640  389-ds-base-2.0 -> 389-ds-base-2.0
b85508b75..d77fe854b  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
