### ISSUE TITLE
wtime can be negative / optime goes very high.

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#5832]
In a customer case on 1.4.4 we have seen wtimes go into negative values with some odd results.

```
[28/Jun/2023:13:43:44.726679117 +0000] conn=587054 op=0 RESULT err=48 tag=101 nentries=0 wtime=-1751600.129697359 optime=1751599.948684335 etime=0.078380136
```

The mathematics of ldap/servers/slapd/operation.c and ldap/servers/slapd/result.c appear sound, and the use of clock_monotonic is correct. This would indicate from my reading that slapi_timespec_diff that b->tv_sec > a->tv_sec. Is this something that we have seen elsewhere? @mreynolds389

**Comment by progier389** [comment]
Hi @Firstyear ,
FYI: I does not ring any bells in my mind.
Since etime seems correct that would means that o_hr_time_rel is invalid and I do not think that there is a path where the value is not set (either to 0 in case of internal operation or in operation_init for the regular operations)
So IMHO the only explanation is the painful one (memory was overwritten either because a buffer overflow or an heap corruption ... )

**Comment by mreynolds389** [comment]
I think this was fixed in newer versions  We have not been maintaining the 1.4.4 branch.  I'll try and find the commit for you...

**Comment by Firstyear** [comment]
It's okay, I can find it, especially if it's already fixed that helps the investigation a lot.

**Comment by mreynolds389** [comment]
> Found it: [a199440](https://github.com/389ds/389-ds-base/commit/a199440a2dd93c20c8e0618c9be424797537426e) from #5322
> 
> No issues if I backport that to 1.4.4? 

Nope, update it as you wish since we don't use it anymore :-)

**Comment by Firstyear** [comment]
Thanks :) I'll try not to back port too much, as we'd prefer people to upgrade here anyway.

**Comment by Firstyear** [comment]
```
To github.com:389ds/389-ds-base.git
   3da9b41ae..578903bab  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
```
